//
// Generated file, do not edit! Created by nedtool 5.6 from customizedMessage.msg.
//

#ifndef __CUSTOMIZEDMESSAGE_M_H
#define __CUSTOMIZEDMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>customizedMessage.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet CustomizedMessage
 * {
 *     \@customize(true);  // see the generated C++ header for more info
 *     char M_Header;
 *     char M_Trailer;
 *     string M_Payload;
 *     int M_Type;
 * }
 * </pre>
 *
 * CustomizedMessage_Base is only useful if it gets subclassed, and CustomizedMessage is derived from it.
 * The minimum code to be written for CustomizedMessage is the following:
 *
 * <pre>
 * class CustomizedMessage : public CustomizedMessage_Base
 * {
 *   private:
 *     void copy(const CustomizedMessage& other) { ... }

 *   public:
 *     CustomizedMessage(const char *name=nullptr, short kind=0) : CustomizedMessage_Base(name,kind) {}
 *     CustomizedMessage(const CustomizedMessage& other) : CustomizedMessage_Base(other) {copy(other);}
 *     CustomizedMessage& operator=(const CustomizedMessage& other) {if (this==&other) return *this; CustomizedMessage_Base::operator=(other); copy(other); return *this;}
 *     virtual CustomizedMessage *dup() const override {return new CustomizedMessage(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from CustomizedMessage_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(CustomizedMessage)
 * </pre>
 */
class CustomizedMessage_Base : public ::omnetpp::cPacket
{
  protected:
    char M_Header;
    char M_Trailer;
    ::omnetpp::opp_string M_Payload;
    int M_Type;

  private:
    void copy(const CustomizedMessage_Base& other);

  public:
    // protected and unimplemented operator==(), to prevent accidental usage
   bool operator==(const CustomizedMessage_Base&);
   // make constructors protected to avoid instantiation
   CustomizedMessage_Base(const char *name=nullptr, short kind=0);
   CustomizedMessage_Base(const CustomizedMessage_Base& other);
   // make assignment operator protected to force the user override it
   CustomizedMessage_Base& operator=(const CustomizedMessage_Base& other);

    virtual ~CustomizedMessage_Base();
    virtual CustomizedMessage_Base *dup() const override {return new CustomizedMessage_Base(*this) ;}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual char getM_Header() const;
    virtual void setM_Header(char M_Header);
    virtual char getM_Trailer() const;
    virtual void setM_Trailer(char M_Trailer);
    virtual const char * getM_Payload() const;
    virtual void setM_Payload(const char * M_Payload);
    virtual int getM_Type() const;
    virtual void setM_Type(int M_Type);
};


#endif // ifndef __CUSTOMIZEDMESSAGE_M_H

